### ISSUE TITLE
Consider omitting the `scope` parameter from `grant_type=authorization_code` token requests

### ISSUE THREAD

**Issue by kevinchalet** [oidcproxydotnet/OidcProxy.Net#163]
Hey,

I hope this ticket will find you well 😄 

I am the main developer of OpenIddict, for which a nice OidcProxy.Net sample was recently added here: https://github.com/oidcproxydotnet/OidcProxy.Net/tree/1cb737ae41b4745e2cbb5aeaf6d9e06bb3f63e3a/docs/demos/spa-bffs/openiddict (thanks for that!)

I see in [the associated wiki documentation](https://github.com/oidcproxydotnet/OidcProxy.Net/wiki/OpenIddict-&-OidcProxy.Net-Exception:-The-'scope'-parameter-is-not-valid-in-this-context.) that there were concerns regarding OpenIddict's handling of the `scope` parameter and that you're recommending removing the built-in `ValidateScopeParameter` handler from the default handlers.

I'd like to clarify that behavior since it seems it's becoming a common source of confusion:
  - `scope` is not a standard token request parameter for the OAuth 2.0 authorization code flow or OpenID Connect hybrid flows, as I demonstrated here: https://stackoverflow.com/a/78200920/542757.
  - Since this parameter is uncalled for in this context, OpenIddict now deliberately rejects `grant_type=authorization_code` - and `grant_type=urn:ietf:params:oauth:grant-type:device_code` - token requests that specify a `scope` parameter.
  - As defined by the OAuth 2.0 specification, OpenIddict allows specifying a `scope` parameter in `grant_type=refresh_token` requests and automatically limits the scope of the returned access token to the requested list (of course, the `scope` parameter cannot contain scopes that were not granted during the authorization request handling).

Since sending a `scope` parameter for `grant_type=authorization_code` is not standard, may I suggest only including it for `grant_type=refresh_token` token requests? This way, removing the built-in `ValidateScopeParameter` handler shouldn't be necessary.

Note: for scenarios where you have no control over what the client sends, I'd recommend adding a custom event handler responsible for removing the `scope` parameter from the request instance (instead of removing the `ValidateScopeParameter` handler). You can find an example at the end of this SO post: https://stackoverflow.com/a/78200920/542757.

All the best.

**Comment by appie2go** [comment]
Hi Kevin,

Thank you very much for your explanation and for taking the time to describe it in such detail. This is definitely something I'll pick up. Unfortunately, I will not be able to pick it up in the next month.

I've noticed that various people/organizations use this framework (oidcproxy.net) with OpenIdDict. So, I think we would both benefit from a seamless integration. For that reason, I would like to work on improving OpenIdDict integration and providing (much) better samples. Therefore, any feedback on those would be greatly appreciated. Would you mind if I reached out to you about that sometime soon?

Cheers,

P.S. Kudos for your work on OpenIdDict. It's awesome!

**Comment by kevinchalet** [comment]
Hey @appie2go,

Ooops, I somehow completely missed your reply, very sorry for that 😕 

> For that reason, I would like to work on improving OpenIdDict integration and providing (much) better samples. Therefore, any feedback on those would be greatly appreciated. Would you mind if I reached out to you about that sometime soon?

Sure, please don't hesitate!

Not sure if you've seen it, but OpenIddict now has a powerful OAuth 2.0+OIDC client that comes with many provider integrations (at the time of writing, `OpenIddict.Client.WebIntegration` already supports ~90 providers).

It was designed to be flexible and universal and can be used in desktop or web apps (in the next version, iOS/macOS and Mac Catalyst will also be supported): as such, it can be an interesting replacement to `Microsoft.AspNetCore.Authentication.OpenIdConnect` (there are multiple samples in the [samples repo](https://github.com/openiddict/openiddict-samples) if you're interested in seeing it in action 😃)

Thanks for addressing the concern mentioned in my OP, it's really appreciated 👍🏻 

Cheers.

**Comment by appie2go** [comment]
Hi!

> Ooops, I somehow completely missed your reply, very sorry for that 😕

Don't worry... It happens!

> Not sure if you've seen it, but OpenIddict now has a powerful OAuth 2.0+OIDC client that comes with many provider integrations (at the time of writing, OpenIddict.Client.WebIntegration already supports ~90 providers).

I did see it, but I haven't looked close enough to consider it as a replacement for `Microsoft.AspNetCore.Authentication.OpenIdConnect`. The reason I am so enthusiastic about OpenIdDict is because you adhere to the OpenId connect standard. So does IdentityServer, and so does KeyCloak. This makes life easy. That's in contrast to Microsoft EntraId. They do everything slightly different. (You have probably experienced this too?) Consequently, maintaining a solution for EntraId is a lot of work. So it would be great if there's a library that takes that work off my plate.

Hence my question: is `OpenIddict.Client.WebIntegration` compatible with EntraId?

Anyways, I will definitely take a closer look! If you have any suggestions, don't hesitate to reach out to me.

> Thanks for addressing the concern mentioned in my OP, it's really appreciated 👍🏻

Sorry it took so long.. 

Cheers!

**Comment by kevinchalet** [comment]
> That's in contrast to Microsoft EntraId. They do everything slightly different. (You have probably experienced this too?)

Haha yeah. But compared to the legacy v1 implementation that was fairly non-standard, the v2 endpoints are much better in this regard. And compared to Azure B2C (whole different product), it's much less painful to support (what a nightmare...)

> Consequently, maintaining a solution for EntraId is a lot of work. So it would be great if there's a library that takes that work off my plate.

While it's quite basic since it's OAuth 2.0-only, `Microsoft.AspNetCore.Authentication.MicrosoftAccount` can help with that. Or you can opt for `Microsoft.Identity.Web`, that wraps the ASP.NET OIDC handler and implements all their custom stuff.
 
> Hence my question: is `OpenIddict.Client.WebIntegration` compatible with EntraId?

It does! https://github.com/openiddict/openiddict-core/blob/b7275df59a2390bd1ba0ca8f3c887ccff8e0252a/src/OpenIddict.Client.WebIntegration/OpenIddictClientWebIntegrationProviders.xml#L1064-L1085

OpenIddict uses the v2 endpoints, so fewer quirks are required to make it work: https://github.com/search?q=repo%3Aopeniddict%2Fopeniddict-core%20ProviderTypes.Microsoft&type=code

**Comment by appie2go** [comment]
Great! I'll look into it!

Thanks very much! :-)
