### ISSUE TITLE
Hook for the YARP pipeline

### ISSUE THREAD

**Issue by ihorwill** [oidcproxydotnet/OidcProxy.Net#186]
Is there a way to add extra middleware to modify the YARP request pipeline, e.g. to add extra headers to be sent to the downstream API?

P.S. thanks for this very useful project.

**Comment by ihorwill** [comment]
I've made the bold step of creating a PR (my first on GitHub). It contains the changes we have made to get it working with our app, using the OpenIdConnect assembly to authenticate with Keycloak.

I have not had time to understand the tests in order to add new ones (and could not get some of the existing tests to run) but all tests that were passing for me on the main branch are still passing.

![image](https://github.com/oidcproxydotnet/OidcProxy.Net/assets/611078/abd98ba1-7732-4720-9bfa-236625f9e486)

**Comment by appie2go** [comment]
Hi there,

Thanks very much for contributing to this project. The community is really what makes the product valuable. 

Sorry about the inconvenience with the test automation. This should be working properly and the pipeline should validate your PR upon submission. (Working on that!)

As you may have seen, I've reviewed your pull request. 

To add the appropriate tests, I would love learn more about your use-case. Could you elaborate?

Thanks again,

Best,

Albert

**Comment by ihorwill** [comment]
Hi Albert, thanks for your fast feedback! I'll get onto the PR comments today.

Our situation is that we are starting to integrate OIDC and OAuth into our established apps which currently use app-managed usernames/passwords and/or Windows authentication with IIS.

I'm at the stage where (thanks to OidcProxy) we are successfully authenticating with Keycloak (configured with Entra Id) but still need to correlate the user against our internal users table - moving all those settings is going to take some time, if it's even feasible.

So as well as the OAuth access token, I have taken the approach of passing an extra token to the downstream APIs. The BFF gateway looks up the user from the identity token, creates a new token with the app-specific user id and other settings, and passes it in an additional HTTP header through YARP. For that we need to add an interceptor into the pipeline.

The APIs validate the access token for primary authorization, and then use the extra token to get the internal user id etc.

For background, we were already using YARP and passing our own token in the authorization header. The fact that OidcProxy integrated with YARP was one of the features that appealed to us (in addition to its elegant BFF design).

Thanks for reading. If you think there's some other way I should be going about this I'd value your insight.

Kind regards,
Ian

**Comment by appie2go** [comment]
Issue was closed due to merging @ihorwill 's pull request, however, there are still testing efforts to be made.

Also, @ihorwill, please confirm the current solution fits your needs or if there's more changes required!

**Comment by ihorwill** [comment]
@appie2go Working well for us now - thanks!

**Comment by appie2go** [comment]
Ok, great! I will add some tests, and ship a release this week.

Cheers!

**Comment by ihorwill** [comment]
Amazing! Many thanks.
