### ISSUE TITLE
Can't find package

### ISSUE THREAD

**Issue by lorinczantonia** [oidcproxydotnet/OidcProxy.Net#194]
dotnet add package GoCloudNative.Bff.Authentication.AzureAd when executing this command I get the following error : "_There are no versions available"._

**Comment by appie2go** [comment]
Hi there,

Thanks for your feedback.

We've rebranded the GoCloudNative.Bff. It's now called OidcProxy.Net. Also Azure AD is now called EntraId. Hence, the package you need to install is:

`dotnet add package OidcProxy.Net.EntraId`.

I assume you ran into this issue after downloading the [demo](https://github.com/oidcproxydotnet/OidcProxy.Net/tree/main/docs/demos/Authentication-Gateways/AzureAd/src/Bff)? 

Cheers

**Comment by lorinczantonia** [comment]
I was following this article: https://medium.com/web-security/implementing-the-bff-security-pattern-with-azuread-b2c-4f340cafecfb

**Comment by appie2go** [comment]
I've updated the article and the [demo](https://github.com/oidcproxydotnet/OidcProxy.Net/tree/main/docs/demos/Authentication-Gateways/AzureAd/src).

Thanks for your feedback!
