### ISSUE TITLE
PKCE verification error following login

### ISSUE THREAD

**Issue by ihorwill** [oidcproxydotnet/OidcProxy.Net#196]
I have been getting this error intermittently. Please see attached log file: [log-20240516-PKCE-error.txt](https://github.com/oidcproxydotnet/OidcProxy.Net/files/15336135/log-20240516-PKCE-error.txt)

I cannot reliably reproduce it, but it appears to happen when logging in and out from different SPAs (with different post-login landing pages) that use the same BFF.

The problem appears to be resolved by deleting the session cookie after logging out. This seems like a good idea anyway, so I'll create a PR for that.

**Comment by appie2go** [comment]
Hi,

Thanks. That's a good point. Removing the session cookie after signing out makes a lot of sense.

I notice there's another issue here too: https://github.com/oidcproxydotnet/OidcProxy.Net/blob/main/src/OidcProxy.Net/Endpoints/CallbackEndpoint.cs

On line 42 it says `await authSession.RemoveCodeVerifierAsync();`. But if an error occurs earlier, the code verifier is not removed. I think the code verifier should always be removed, so I think it should be in the `finally` block instead.

Also, please note that i've added a lot of new tests. All integration tests should now pass on your machine, except the auth0 test. 

Thanks again for your contribution. Looking forward to seeing your PR.

**Comment by ihorwill** [comment]
Thanks for the super-fast response!

Are you happy for me to include that change in the PR?

The tests do indeed all pass except for the Auth0 integration test. Great work!

Am happy to contribute in this small way. Thanks for an awesome library that has helped us (me) implement an important feature. I look forward to getting to know it better.

**Comment by appie2go** [comment]
Hi Ian,

Glad I could help. And as you may have noticed, I do a lot of this work in my spare time. So, I appreciate your help a lot. Thanks!

Unfortunately, I don't have time to test and release this increment this week. So, expect it to be in the version I'll release next week.

Thanks again,

Cheers,

**Comment by ihorwill** [comment]
Thanks Albert, look forward to it.

Since we're using Keycloak I'll have a stab at setting up a demo for it (ref issue #8).

**Comment by appie2go** [comment]
Hi Ian,

The pull-request is merged, tested, and included in release 3.2.2.

Closing the issue :-)

Thanks again for your contribution!
