### ISSUE TITLE
Suggestion for Improvement: Could you make class AuthSession public ?

### ISSUE THREAD

**Issue by Alism0** [oidcproxydotnet/OidcProxy.Net#213]
Hello) 
Thank you for your work once again) 
I noticed that you added the Middleware: 
src/OidcProxy.Net/Middleware/AnonymousAccessMiddleware.cs 
which, if anonymous access is disabled, 
- saves the requested current path (SetUserPreferredLandingPageAsync), 
- redirects for authentication, 
- and after authentication, redirects to the saved request in the session.
I implemented similar logic for our solution:
![ARCH  BFF with Secure SPA Part](https://github.com/oidcproxydotnet/OidcProxy.Net/assets/22932071/84b76c60-c5bf-4140-b40d-3c38eece6c26)

We had the following problems: 
Case 1: 
The user visits the site for the first time 
1. In the custom middleware, we save the requested path to the session 
2. We redirect to the account/login endpoint for authentication (a bit of a workaround since for some reason I didn't think that I could reproduce the logic from LoginEndpoint))
3. In the custom implementation of IAuthenticationCallbackHandler, we redirect to the saved path (step 1) upon successful login.
In this case, everything worked fine.

Case 2: 
The user opens the browser with a cached page: 
1. In the browser, index.html is executed: 
requests for js bundles, manifest.json, css, etc., begin to execute. 
2. Problem 1: 
Parallel requests arrive at BFF - all sessions are invalid, and a new session is created for each, initiating the authentication flow. 
This often resulted in "PKCE invalid code verifier" errors in the production environment (I saw your last "PKCE verification failed" fix and maybe it help- haven't had a chance to test it yet, but thank you) 
3. Problem 2: Requests for js bundles, manifest.json, css files were saved in the session, and after authentication, instead of redirecting to the base SPA route, the content of these files was displayed.

Solution for Problem 1: 
Added a check for requests in custom middleware (configurable via config) - if the request path starts with paths specified in the config, such as /static/css... or /manifest.json, those requests should have anonymous access. 
For other paths (e.g., initializing SPA on the front-end at /static/js/...), authentication is required, and if the user is not authenticated, a redirect to account/login is performed. 
For /static/js/..., a check is required to prevent unauthorized attempts to obtain js.bundle, but that's a different story))

Solution for Problem 2: 
Also added a check for requests in custom middleware, configurable via config: if requests start with, for example, /static/..., do not save them for redirecting. 
And in IAuthenticationCallbackHandler, redirect to "/" for this requests.

So, I have the following questions:
1. Could you make class AuthSession public so that we can replicate the logic from LoginEndpoint/AnonymousAccessMiddleware 
await _authSession.SetCodeVerifierAsync(authorizeRequest.CodeVerifier); 
and then in the code, redirect not to account/login 
but to authorizeRequest.AuthorizeUri.
Consequently, it would be great if there was an option to enable/disable using AnonymousAccessMiddleware (although this can generally be controlled via the AllowAnonymousAccess setting, but it might not be obvious to an uninitiated user).

2 Ideally, I would like to completely remove my custom middlewares and use your implementation entirely. 
But at the moment, I'm concerned about problems 1 and 2, and it seems the current out-of-the-box solution doesn't cover these cases (parallel unauthenticated requests and saving only application routes (not requests to /api/..., /static/..., etc.)) to the session. 
So, the second question is, have you encountered similar cases? Have you developed a solution for this?

**Comment by Alism0** [comment]
I would like to: 
1. Have the ability to enable/disable AnonymousAccessMiddleware or completely override it. This would allow, for example, adding filtering logic for some routes for anonymous access. 
2. Have the ability to work with sessions through your methods: It would be helpful to call SetUserPreferredLandingPageAsync, so we don't have to write our own logic for saving the route in the session and override IAuthenticationCallbackHandler (essentially reinventing the wheel when you already have the necessary method). 
3. It would be useful to obtain the AuthorizeUri so that we can redirect to the identity provider instead of .auth/login (a workaround on my end).

Give developers more freedom, but with a note that they do so at their own risk)

**Comment by appie2go** [comment]
My pleasure. I will see what I can do! Let me come back to you with a tangible approach and validate if it's a feasible solution for you.

**Comment by Alism0** [comment]
Thanks a lot) 
Looks like what we need)
I'm on vacation now: in a week and a half I'll check whether this update solves my case)

**Comment by appie2go** [comment]
@Alism0, regarding your comment about excluding the /dist folder: if you are going to build such middleware, please consider sharing it in a pull request!

Thanks in advance!
