### ISSUE TITLE
OidcProxy.Net.EntraId RefreshToken Fails if custom API Scope is used

### ISSUE THREAD

**Issue by martbrugg** [oidcproxydotnet/OidcProxy.Net#238]
Hi,

i have the following Problem that the RefreshToken Request fails with 400 and the message: 
`Application <APPLICATION ID> is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.`

During my research i found the reason. The problem is that the refresh token request does not contain the Scope parameter.
If i add the scope to the RefreshTokenRequest in **OpenIdConnectIdentityProvider** it works:

`
public async Task<TokenResponse> RefreshTokenAsync(string refreshToken, string traceIdentifier)
{
    var openIdConfiguration = await GetDiscoveryDocument();
    var scopes = new Scopes(configuration.Scopes);

    var response = await httpClient.RequestRefreshTokenAsync(new RefreshTokenRequest
    {
        Address = openIdConfiguration.token_endpoint,
        GrantType = OidcConstants.GrantTypes.RefreshToken,
        RefreshToken = refreshToken,
        ClientId = configuration.ClientId,
        ClientSecret = configuration.ClientSecret,
        Scope = string.Join(' ', scopes)
    });
        
`

**Comment by appie2go** [comment]
Hi there,

Thanks. Makes sense. Great work!
