### ISSUE TITLE
Register identity provider that extends OpenIdConnectIdentityProvider

### ISSUE THREAD

**Issue by RafalOsieka** [oidcproxydotnet/OidcProxy.Net#240]
I have a custom IdentityProvider class implementation, that overrides one method in OpenIdConnectIdentityProvider.

Currently there is no easy way of registering such implementation using the `AddOidcProxy` method (https://github.com/oidcproxydotnet/OidcProxy.Net/blob/main/src/OidcProxy.Net.OpenIdConnect/ModuleInitializer.cs#L27).

It would be great to have a generic AddOidcProxy method that allows to register custom identity provider implementation instead of the default OpenIdConnectIdentityProvider.

**Comment by appie2go** [comment]
Hi Rafal,

Thanks for your comment. And I agree. It's too complicated.

Assume anything is possible. Do you have a preference what the interface for registering an identityprovider should look like?

Cheers!

**Comment by RafalOsieka** [comment]
Assuming I have a custom identity provider `class MyIdentityProvider : OpenIdConnectIdentityProvider { ... }`, then in the Program.cs I would like to configure it in the following way `builder.Services.AddOidcProxy<MyIdentityProvider>(oidcProxyConfig)`.

This is enough for my use case, but maybe it would be good to have the possibility to have custom config. Hypothetically, `MyIdentityProvider` uses `class MyOidcProxyConfig : OidcProxyConfig { ... }`, then I would like to configure it the same way, i.e. `builder.Services.AddOidcProxy<MyIdentityProvider, MyOidcProxyConfig>(myOidcProxyConfig)`.

I think the following signature should be ok
```csharp
public static IServiceCollection AddOidcProxy<TOpenIdConnectIdentityProvider, TOpenIdConnectConfig>(this IServiceCollection serviceCollection, TOpenIdConnectConfig config, Action<ProxyOptions>? configureOptions = null)
    where TOpenIdConnectIdentityProvider : OpenIdConnectIdentityProvider
    where TOpenIdConnectConfig : OpenIdConnectConfig
{
    // later the services.ConfigureOpenIdConnect... is called - it should have similar signature
}
```

It allows to configure custom idp/options, but forces to use the base implementations (OpenIdConnectIdentityProvider/OpenIdConnectConfig).

NOTE: my use case uses the OpenIdConnectIdentityProvider. Probably the same should be done for the rest providers as well (EntraId, Auth0)

**Comment by appie2go** [comment]
Hi there,

Picked up this item. Working on it, will get back to you in two weeks at max.

Stay tuned..

Cheers

**Comment by appie2go** [comment]
Hi there,

It took some time, sorry for that. As you may have noticed, there was some tech-dept in the area where the change had to be implemented. 

Anyways, I've implemented a method that allow you to do something like this:

```csharp
using OidcProxy.Net;
using OidcProxy.Net.ModuleInitializers;
using OidcProxy.Net.OpenIdConnect;

var builder = WebApplication.CreateBuilder(args);

var config = builder.Configuration
    .GetSection("OidcProxy")
    .Get<OidcProxyConfig>();

builder.Services
    .AddOidcProxy<YourOpenIdConnectIdentityProvider, ProxyConfig>(config);

var app = builder.Build();

app.UseOidcProxy();

app.Run();
```

Hope this suits your needs. If not, please let me know, then we'll reopen the ticket!

I'll ship this change in version 5.1.0. which will ship this week.

Cheers
