### ISSUE TITLE
Client app fails to build when template is upgraded from version 0.0.3 to 0.0.4

### ISSUE THREAD

**Issue by AdityaSingh007** [oidcproxydotnet/OidcProxy.Net#271]
Hello Team,

I have upgraded the template from version 0.0.3 to 0.0.4 , when I run the command install packages for client app I get below error:-

npm error code 1
npm error path C:\Angular_BFF_Authentication\ClientApp\node_modules\lmdb
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build-optional-packages
npm error C:\Angular_BFF_Authentication\ClientApp\node_modules\node-gyp-build-optional-packages\node-gyp-build.js:85
npm error   throw new Error(errMessage)
npm error   ^
npm error
npm error Error: No native build was found for platform=win32 arch=x64 runtime=node abi=127 uv=1 libc=glibc node=22.5.1
npm error     attempted loading from: C:\Angular_BFF_Authentication\ClientApp\node_modules\lmdb and package: @lmdb/lmdb-win32-x64
npm error Error resolving package: Cannot find module '@lmdb/lmdb-win32-x64'
npm error Require stack:
npm error - C:\Angular_BFF_Authentication\ClientApp\node_modules\lmdb\package.json
npm error
npm error     at load.resolve.load.path (C:\Angular_BFF_Authentication\ClientApp\node_modules\node-gyp-build-optional-packages\node-gyp-build.js:85:9)       
npm error     at load (C:\Angular_BFF_Authentication\ClientApp\node_modules\node-gyp-build-optional-packages\node-gyp-build.js:28:30)
npm error     at Object.<anonymous> (C:\Angular_BFF_Authentication\ClientApp\node_modules\node-gyp-build-optional-packages\build-test.js:19:19)
npm error     at Module._compile (node:internal/modules/cjs/loader:1504:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1282:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1098:12)
npm error     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
npm error     at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
npm error
npm error Node.js v22.5.1
npm error
npm error The failure above indicates the primary issue with the native builds which are included for all major platforms. Will now attempt to build the package locally in case this can be resolved by re-compiling.
npm error 'C:\Program' is not recognized as an internal or external command,
npm error operable program or batch file. 

Please see below for versions used:-
**Node - 22.5.1**
**OidcProxy.Net template version - 0.0.4**

Please let me know if any further information is required to resolve above issue.

**Comment by appie2go** [comment]
Hi!

Thanks for your feedback, sorry for the inconvenience... Please try removing the `node_modules` folder and try again?

Cheers,

**Comment by appie2go** [comment]
Thanks for trying that. What version of Angular are you using?

**Comment by AdityaSingh007** [comment]
Please see below for version of angular installed:-
![angularversion](https://github.com/user-attachments/assets/d26a6c62-e534-44f8-a5d2-6c9499ab1c95)

**Comment by appie2go** [comment]
I see... the template requires angular 18. Can you please see if installing the latest angular cli fixes the problem?

**Comment by appie2go** [comment]
Hi,

Thank you for pointing this out. Turns out the issue is caused by package-lock.json which should not be included in the project that has been scaffolded. So, if you remove package-lock.json, everything should work fine.

In the mean while I will work on a patch that solves the issue and excludes the package-lock.json file from the template.

Thanks again!
