### ISSUE TITLE
Add documentation for wiring this project with KeyCloak

### ISSUE THREAD

**Issue by appie2go** [oidcproxydotnet/OidcProxy.Net#8]
This project contains several samples that demonstrate how to use this library. Currently, there is a demo for IdentityServer4, Auth0, and AzureAd. However, various users of this library are using it with KeyCloak. Therefore, we need a demo that describes and illustrates how to use this library with KeyCloak.

Currently the demo's look like so:
* https://github.com/thecloudnativewebapp/GoCloudNative.Bff/tree/main/docs/demos/Authentication-Gateways
* https://github.com/thecloudnativewebapp/GoCloudNative.Bff/tree/main/docs/demos/spa-bffs

Request:
* Please add a demo similar to the ones this project already contains, with KeyCloak
* Preferably, users are able to download the sample and run it without configuring too much

**Comment by Thorvaldd** [comment]
Oh, it's bad, that it has been closed. I'm working right now with keycloak, and for now successfully integrated BFF with it. Just configured appsettings and keycloak bff client and use example spa app. 
Maybe there are things which I need to know when I will move further with keycloak integration.

**Comment by appie2go** [comment]
Hi Thorvaldd,

Let me know if you run in to anything, we can reopen this ticket if need be.

Cheers

**Comment by appie2go** [comment]
Reopening this issue because more and more people are starting to use this library in combination with KeyCloak.

**Comment by ihorwill** [comment]
Created PR #199  for a Keycloak SPA+BFF demo.
